#!/bin/bash
set -eux
# This is designed to work on circleci.com with a parallelism of 3.
HERE=$(dirname $(readlink -f $0))

make clean
case $CIRCLE_NODE_INDEX in
    # these are the platforms that I care about.
    0) base=debian:sid ;;
    1) base=ubuntu:trusty ;;
    2) base=ubuntu:precise ;; # for travis
    3) base=ubuntu:lucid ;;
    *)
        echo unknown CIRCLE_NODE_INDEX: $CIRCLE_NODE_INDEX
        exit -1
        ;;
esac

$HERE/generic $base $CIRCLE_ARTIFACTS/$base
