#!/bin/bash
set -eux
# the basic functionality of CI: build the debs, put them somewhere.
base="$1"
dest="$2"

sed -i "1 s/.*/FROM $base/" Dockerfile

make docker-debs

mkdir -p $dest
cp *.{deb,debian.*,dsc,build,changes,info.txt} $dest
